[package]
name = "soa_bench"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
soa_derive = "0.12.0"
derive_more = "0.99.16"

[dev-dependencies]
num = "0.4.0"
